# incoming_players_data_2025.py
"""
Incoming players (freshmen) for the 2025 season.

Valid Date Range: August 1, 2024 - July 31, 2025

Format:
Conference Name:
Player Name - School Name - Position (Club)
"""

RAW_INCOMING_TEXT_2026 = """
America East Conference:
Addy Bianchini - University at Albany - Setter/OPP (NKYVC)
Lily Lott - University at Albany - OH/OPP (Houston Skyline)
Sophia Christoffers - Binghamton University - OH (Sideout Sports)
Ava Gaspard - Binghamton University - OH (Sideout Sports)
Sydney Geselbracht - Binghamton University - MB (Elevation)
Luiza Bergamaschi - Bryant University - Libero/DS (305 Volleyball Club)
Sophia Gonzalez - Bryant University - OPP/OH (Miami Volleyball Academy)
Alicia Johansen - Bryant University - MB (Premier Nebraska)
Cara Lewandowski - Bryant University - OH (Niagara Frontier)
Layla Olatunde - Bryant University - MB (Integrity)
Laura René-Fraser - Bryant University - Setter (International: Canada)
Megan Hunter - University of Maryland, Baltimore County - Setter (International: Canada)
Dasia Johnson - University of Maryland, Baltimore County - OH (Wildfire Volleyball Academy)
Elly VanLandingham - University of Maryland, Baltimore County - Libero/DS (Metro)
Avery Albritton - University of New Hampshire - OPP (Sky High)
Ava Hartman - University of New Hampshire - Setter/DS (Tstreet IE)
Caitlin Leddy - University of New Hampshire - Setter/OPP (1st Alliance)
Lauren McCarthy - University of New Hampshire - Libero/DS (OTVA)
Leah Devaraj - New Jersey Institute of Technology - OH/OPP (TAV)
Mya Lei-Butters - New Jersey Institute of Technology - Libero/DS (Iowa Power Plex)

American Athletic Conference (AAC):
Ingrid Dittmar - University of Alabama at Birmingham - Setter (Elite VBTC)
Makayla Meister - University of Alabama at Birmingham - OH (Buckeye VBC)
Payton Sirdine - University of Alabama at Birmingham - OH/OPP (Husky)
Clara Cloninger - East Carolina University - OH (Coast United)
Jaci Hall - East Carolina University - OH/OPP (Alamo)
Kanani Magee - East Carolina University - OPP/OH (Tsunami)
Brook Watkins - East Carolina University - Setter (Triangle)
Chloe Garcia - Florida Atlantic University - Setter/OPP (Tribe)
Isabella Johnson - Florida Atlantic University - OH/OPP (OTVA)
Bre Morgan - Florida Atlantic University - MB (Boiler Juniors)
Brooklyn Bailey - University of Memphis - MB/OPP (TAV)
Dawn Moore - University of Memphis - OPP/Setter (Madfrog)
Kaylee Parker - University of Memphis - OH/OPP (Houston Juniors)
Jordan Turner - University of Memphis - Setter (Excel)
Clara Briley - University of North Carolina at Charlotte - OH (A5)
Milan Cannon - University of North Carolina at Charlotte - MB (A5)
Kennedy Earls - University of North Carolina at Charlotte - Libero/DS (Sunshine)
Cassidy Flakes - University of North Carolina at Charlotte - MB (Winter Park)
Dixie Gayden - University of North Carolina at Charlotte - Setter (Dallas Skyline)
Olivia Branum - University of North Texas - Setter (Oklahoma Peak)
Paige Hawkinson - University of North Texas - Setter (TAV)
Madi Smith - University of North Texas - OH (NORCO)
Alyssa Young - University of North Texas - Libero/DS (KC Power)
Zora Bello - Rice University - Setter (Houston Juniors)
Declan Eastman - Rice University - Libero/DS (Sunshine)
Bella Lopez - Rice University - OH/OPP (Madfrog)
Ashlyn Seay - Rice University - OH (Dallas Skyline)
Riley McCaughey - University of South Florida - Setter (Tribe)
Cate Palmi - University of South Florida - OH (Game Point)
Annemarie Perez - University of South Florida - MB (Miami Hype)
Kennedy Crayton - Temple University - OH (Madfrog)
Leah Hampson - Temple University - OH (Synergy)
Sarah Quarells - Temple University - MB/OPP (West Florida Waves)
Lily Smith - Temple University - MB (Milwaukee Sting)
Maddix Taniguchi - Temple University - Libero/DS (Ku'ikahi)
Logan McGinnis - University of Texas at San Antonio - OH (United)
Harmoni Dobbins - Tulane University - MB/OPP (TK Volleyball)
Maggie Kalisz - Tulane University - OH/MB (M1)
Kailey Leonard - Tulane University - Libero/DS (TK)
Mariel St. John - Tulane University - MB/OPP (Miami Hype)
Charlotte Strickland - Tulane University - Setter (SC Elite)
Lexi Dahl - University of Tulsa - Setter (STVA)
Michaelyn Freeman - University of Tulsa - OH (Ozark Juniors)
Rachel Megna - University of Tulsa - Libero/DS (Oklahoma Peak)
Sophia Gilbert - Wichita State University - MB (Aspire)
Brea Martin - Wichita State University - Libero/DS (Shockwave)
Kate Mobley - Wichita State University - OH (Zona)
Addie Oeth - Wichita State University - Setter (Sting United)
Olivia Stein - Wichita State University - OH (Primetime)

Atlantic 10 Conference:
Peyton Garrick - Davidson College - Libero/DS (USA South)
Abbie Henson - Davidson College - OH (Michio Chicago)
Geli St Laurent - Davidson College - OPP (1United)
Myla Young - Davidson College - MB (NYC Juniors)
Sienna Fry - University of Dayton - OPP (Summit)
Natalie Harrington - University of Dayton - Setter (Mintonette)
Ava Liening - University of Dayton - MB (MAVA)
Sidney Sprada - University of Dayton - OH/DS (Elevation)
Charlotte Arrington - Duquesne University - OH/DS (Paramount)
Maddie Bush - Duquesne University - MB (East Coast Power)
Keely McMahon-Regan - Duquesne University - Setter (Pittsburgh Elite)
Simone Searles - Duquesne University - OPP (A5)
Londyn Stone - Duquesne University - OH (AVC)
Jenna Hunt - Fordham University - MB (Vision)
Julianne Lee - Fordham University - OH (Sudden Impact)
Avery Lim - Fordham University - Setter (AZ Storm)
Ady Bollinger - George Mason University - Libero/DS (Ozark Juniors)
Rylee Kinnell - George Mason University - OH (AVC)
McKenna Reynolds - George Mason University - Setter (Husky)
Simone Assasie - George Washington University - MB (Metro)
Evie Huang - George Washington University - Libero/DS (Metro)
Mackenzie Krzus - George Washington University - Setter (Sports Performance)
Tenley Davis - Loyola University Chicago - OH/OPP (1st Alliance)
Camryn Hughes - Loyola University Chicago - MB (Chi City)
Sophia Chinetti - University of Rhode Island - OH/OPP (Adversity)
Kiara Copeland - University of Rhode Island - Libero/DS (Northeast)
Grace Keaney - University of Rhode Island - OPP/MB/OH (Maine Juniors)
Jahan Lalli - University of Rhode Island - Setter (A5)
Cara Richter - University of Rhode Island - OH (Elevation)
Carly Thomas - University of Rhode Island - Setter (Moco Mavs)
Avery Boehm - Saint Louis University - OH/OPP (Blue Steel)
Jordan Baksh - Virginia Commonwealth University - Libero/DS (OTVA)
Molly McCall - Virginia Commonwealth University - OH (Richmond VBC)

Atlantic Coast Conference (ACC):
Chloe Allcroft - Boston College - MB (Absolute)
Laney Blevins - Boston College - MB (NC Volleyball Academy)
Ava Castro - Boston College - OH (Jupiter Elite)
Mia Gold - Boston College - OH (Tribe)
Ava McBride - Boston College - Setter/OPP (Actyve)
Tiani Shaw - Boston College - Libero/DS (SC Rockstar)
Anna Flores - University of California, Berkeley - Setter (TAV)
Siena MacCudden - University of California, Berkeley - Libero/DS (Milwaukee Sting)
Nicole Milosevic - University of California, Berkeley - OH/OPP (International: Canada)
Abby Zimmerman - University of California, Berkeley - OH/OPP (SC Rockstar)
Maddie Anspaugh - Clemson University - OH (VC United)
Lucy Maloney - Clemson University - Libero/DS (1st Alliance)
Ihuoma Ozoh - Clemson University - MB (1st Alliance)
Riley Copenhaver - Duke University - MB/OPP (Legacy)
Carlyle Johnson - Duke University - OH/OPP (Shockwave)
Sara Lozano - Duke University - OH (IMG Academy)
Bennett Raterman - Florida State University - MB (High Performance STL)
Allie Abernathy - Georgia Institute of Technology - MB/Setter (SC Elite)
Vitoria Belfort - Georgia Institute of Technology - Libero/DS (Tribe)
Riley Bethea - Georgia Institute of Technology - MB (A5)
Simone Heard - Georgia Institute of Technology - OH/OPP (Dallas Skyline)
Amirra Bailey - University of Louisville - MB (Tennessee Performance)
Jordyn Gray - University of Louisville - OH (Carolina Juniors)
Elsi Karjanlahti - University of Louisville - Libero/DS (International: Finland)
Elli Strecker - University of Louisville - MB (Team Indiana)
Blair Thiebaud - University of Louisville - Setter (Houston Skyline)
Denitsa Angelova - University of Miami - MB (International: Bulgaria)
Madison Brown - University of Miami - S (Academy Volleyball Club)
Ruth Martínez - University of Miami - OH (305 Volleyball Club)
Ella Thompson - University of Miami - OH (Athena Volleyball Academy)
Stalena Van Deusen - University of Miami - Libero/DS (East Coast Power)
Carly Markham - University of North Carolina - Libero/DS (Triangle)
Lindley Miller - University of North Carolina - OPP (Triangle)
Addison West - University of North Carolina - OH (Premier Nebraska)
Norah Busch - North Carolina State University - MB (East Coast Power)
Callie Combs - North Carolina State University - Libero/DS (NKYVC)
Makenna Kowren - North Carolina State University - OPP (Revolution Volleyball Academy)
Eva Long - North Carolina State University - Setter (Legacy)
Britni Silver - North Carolina State University - OH (East Carolina Juniors)
Carla Mercado - University of Notre Dame - Libero/DS (Puerto Rico)
Isabella Sangha - University of Notre Dame - MB (Tribe)
Portia Zeidler - University of Notre Dame - MB (Vision)
Isabelle Hoppe - University of Pittsburgh - Setter (AVC)
Lola Sageer - University of Pittsburgh - OH (VolleyFX)
Jessica Smallwood - University of Pittsburgh - OPP (KIVA)
Trinity Thompson - University of Pittsburgh - Setter/DS (Vegas Aces)
Ayanna Watson - University of Pittsburgh - OH (Vegas Aces)
Ana Nastase - Southern Methodist University - Setter (International: Canada)
Levariya Pinder - Southern Methodist University - OH (Dallas Skyline)
Victoria Shupe - Southern Methodist University - Libero/DS (Houston Skyline)
Elle Vandeweghe - Southern Methodist University - MB (SC Rockstar)
Ella Andrews - Stanford University - MB (Legacy)
Sarah Hickman - Stanford University - OPP (Houston Juniors)
Simone Roslon - Stanford University - OH (SC Rockstar)
Joy Udoye - Stanford University - OH (Austin Skyline)
Charis Burge - Syracuse University - Setter (Metro)
Kiera Hagler - Syracuse University - MB (Alabama Performance)
Queen Howse - Syracuse University - Libero/DS (Tennessee Performance)
Aileen McAllister - Syracuse University - OH (International: Japan)
Shaye Teves - Syracuse University - Setter (808 Athletic Club)
Gabriella Brodner - University of Virginia - OH/OPP (Jupiter Elite)
Skyler Gates - University of Virginia - MB (Rise Volleyball Academy)
MaryGrace Gonyeau - University of Virginia - OH (Triangle)
Ruby McDermott - University of Virginia - Libero/DS (A5)
Olivia Siskin - University of Virginia - Setter (A5)
Courtney Burgess - Virginia Tech - Setter (Armor)
Avery Feltes - Virginia Tech - OH (Illini Elite)
Isabella Lopez - Virginia Tech - OH (OTVA)
Santina Martcheva - Virginia Tech - OH (Beach Elite)
Cece Sayles - Virginia Tech - MB (No Name)
Avery Webb - Virginia Tech - Libero/DS (OTVA)
Emma Keeping - Wake Forest University - Setter (Michigan Elite)
Ava Roddey - Wake Forest University - Setter (Stars Carolinas)
Mattea Saunders - Wake Forest University - Libero/DS (AZ Storm)
Lyla Stewart - Wake Forest University - OPP (Mintonette)

Atlantic Sun Conference (ASUN):
Maddie Carnes - Bellarmine University - Setter (Union)
Ava Long - Bellarmine University - DS/OH (Elevation)
Mady Yaden - Bellarmine University - MB (KIVA)
Ava Theiller - Florida Gulf Coast University - OH/OPP (East Coast Power)
Daiangelie Gonzalez - Jacksonville University - OH (Puerto Rico)
Aaliyah Mixon - Jacksonville University - OH (Drive Nation)
Selah Simien - Jacksonville University - Libero/DS (Dynasty)
Jaylyn Tuiasosopo - Jacksonville University - OH (STVA)
Grace Jones - Lipscomb University - Libero/DS (Tri-State Elite)
Makenna Kirlin - Lipscomb University - Setter (Elevation)
Madyson McCarthy - Lipscomb University - OH (WAVE)
Charlotte Routh - Lipscomb University - MB (Mintonette)
Sasha Bespaly - University of North Florida - MB (Houston Skyline)
Haydin Froehlich - University of North Florida - Setter (OTVA)
Daisy Oatsvall - University of North Florida - OH (Alliance)
Brooklyn Stringfellow - University of North Florida - Libero/DS (Tejas)
Lydia Chambers - Queens University of Charlotte - MB (Carolina Union)
Naomi Cole - Queens University of Charlotte - OPP (Mintonette)
Ella Hale - Queens University of Charlotte - OH (OK Charge)
Grace Hargis - Queens University of Charlotte - Setter (Circle City)
Josephine Seekford - Queens University of Charlotte - OH (Virginia Elite)
Sophie Jones - Stetson University - Libero/DS (DME)
Keely Pou - Stetson University - Setter (OTVA)
Keely Starnes - Stetson University - MB (Winter Park)
Soraya Teston -  Stetson University - OPP (OTVA)
Sofia Sierra - University of West Georgia - Setter/DS (OTVA)
Caroline Smth - University of West Georgia - Libero/DS (Carolina Rogue)

Big 12 Conference:
Hayden Reeder - University of Arizona - OH (Minnesota Select)
Marina Vosloo - University of Arizona - MB (WAVE)
Gigi Whann - University of Arizona - Libero/DS (TAV)
Ella Hope - Arizona State University - MB (International: Canada)
Paige Lehman - Arizona State University - Libero/DS (Winter Park)
Grace Martin - Arizona State University - OH (Pohaku)
Elle Mottola - Arizona State University - Setter (Winter Park)
Halle Bills - Baylor University - OH (Club V)
Mya Hemmer - Baylor University - MB (FC Elite)
Julianna Hernandez - Baylor University - Libero/DS (TAV)
Nadiya Johnson - Baylor University - OH (Metro)
Abby Schoene - Baylor University - Setter (Rockwood Thunder)
Lacy Tinnell - Baylor University - MB (Houston Skyline)
Kylie Buttars - Brigham Young University - OH (Club V)
Lauren Duncan - Brigham Young University - Setter (Alliance)
Brooke Hardy - Brigham Young University - MB (Idaho Crush)
London Adkins - University of Central Florida - MB (Game Point)
Natasha Casey - University of Central Florida - OPP (OTVA)
Lily Hayward - University of Central Florida - OH (Emerald Coast)
Deana Petrov - University of Central Florida - MB (New Waves)
Malayna Boyles - University of Cincinnati - OH (TAV)
Kayla Edginton - University of Cincinnati - OPP (East Coast Power)
Julia Horan - University of Cincinnati - MB (Virginia Juniors)
Lily Rolfes - University of Cincinnati - Setter (AZ Storm)
Kensley Hennessy - University of Colorado - MB (WAVE)
Dumebi Okoye - University of Colorado - OH (International: Canada)
Barbora Rakauskaitė - University of Colorado - MB (International: Lithuania)
Elle Richardson - University of Colorado - Setter (Elevate Athletics)
Shannon Dworaczyk - University of Houston - Setter (TAV Houston)
Cali Reece - University of Houston - Libero/DS (TAV Houston)
Leah Robinson - University of Houston - OH (MAVS KC)
Ava Wilkerson - University of Houston - MB (NC Volleyball Academy)
Katie Byergo - Iowa State University - MB/OPP (High Performance STL)
Ella Florez - Iowa State University - Setter (Pohaku)
Taylor Johnson - Iowa State University - MB (Houston Skyline)
D'Aaliyah Kemp - Iowa State University - MB (Rev Volleyball Academy)
Reese Naeve - Iowa State University - OH (Iowa Rockets)
Cydnee Bryant - University of Kansas - MB
Tessa Dodd - University of Kansas - OH/OPP (NORCO)
Avery Poulton - University of Kansas - OH (Club V)
Jaeli Rutledge - University of Kansas - MB (Ozark Juniors)
Ryan Sadler - University of Kansas - OH (A5)
Taylor Stanley - University of Kansas - OPP (Dynasty)
Skylar Brady - Kansas State University - OH (Oklahoma Peak)
Ellah Derrer - Kansas State University - MB (Iowa Select)
Addison Massey - Kansas State University - OH (Texas Performance-El Paso)
Reese Resmer - Kansas State University - MB (Boiler Juniors)
Morgan Holloman - Texas Christian University - MB (Colorado Juniors)
Josie Valgus - Texas Christian University - Setter (NC Volleyball Academy)
Kinsley Young - Texas Christian University - MB (TAV)
Elia Dinsmore - Texas Tech University - OH (Tennessee Performance)
Ally Fausett - Texas Tech University - Setter/OPP (A4)
Ava Johnson - Texas Tech University - Libero/DS (Colorado Juniors)
Faith Jordan - Texas Tech University - MB (Sports Performance)
Aviya Russo - Texas Tech University - OH (Vision)
Suttyn Harris - University of Utah - OH (Fight Club)
Nula Anderson - West Virginia University - OH (Empire)
Cassie Bruns - West Virginia University - Libero/DS (Milwaukee Sting)
Cami Huff - West Virginia University - MB (Lower Alabama)
Camden Rahn - West Virginia University - OH (OTVA)
Macie Smith - West Virginia University - OH/OPP (The Academy)
Reagan Turk - West Virginia University - Libero/DS (Team Indiana)

Big East Conference:
Karen Dutro - Butler University - MB (Rev Volleyball Academy)
Lucy Gray - Butler University - OPP (Milwaukee Elite)
Chase Lemming - Butler University - OH/DS (Boiler Juniors)
Taylor Wathen - Butler University - OH (MAVA)
Sydney Borowy - University of Connecticut - OH (AVC)
Abigail Buckner - University of Connecticut - Libero/DS (Milwaukee Sting)
Megan Evans - University of Connecticut - OH (Jersey Juniors)
Courtney Grayson - University of Connecticut - MB (IMG Academy)
Isabella Sohl - University of Connecticut - Setter (High Performance STL)
Bailey Boeve - Creighton University - OH (MVP Volleyball)
Peyton Carlson - Creighton University - Libero/DS (FC Elite)
Rayna Christiansen - Creighton University - Setter (Northern Lights)
Cambel Drapeau - Creighton University - MB (Adrenaline)
Sage Meidroth - DePaul University - Libero/DS (Actyve)
Lexi Anderson - Georgetown University - OH (1United)
Avery Lewis - Georgetown University - MB (The Academy)
Addie Lloyd - Georgetown University - MB (Madfrog)
Olivia Penske - Georgetown University - Setter (Sunshine)
Allie Beers - Marquette University - OPP (Milwaukee Sting)
Caydence Doolan - Marquette University - OH/OPP (Metro)
Aubrey Hicks - Marquette University - MB/OPP (Milwaukee Sting)
Molly Welge - Marquette University - MB (1st Alliance)
Lyla Buser - Providence College - OPP (Jupiter Elite)
Ellie Chu - Providence College - Setter (SC Rockstar)
Ava Dyer - Providence College - Libero/DS (TAV)
Aubrey Easterwood - Providence College - MB (TAV)
Gwyneth Koss - Providence College - OH (Houston Skyline)
Gia Sergi - Seton Hall University - Libero/DS (USANY)
Samantha Shelton - Seton Hall University - OH (1st Alliance)
Maggie Carcillo - St. John's University - Setter (Jersey Juniors)
Teodora Stamenkovic - St. John's University - MB (Metro)
Michelle Eburuoh - Villanova University - MB (Ronin Lotus NJ)
Chloe Kelly - Villanova University - OH (Austin Juniors)
Selah O'Connor - Villanova University - Setter (Revolution Volleyball Academy)
Addison Haberthy - Xavier University - Setter (Circle City)
Sadie Kroeger - Xavier University - OH (Rhythm Volleyball Academy)
Gabby Semona - Xavier University - MB (Tri-State Elite)
Cami Sher - Xavier University - OH (KC Power)

Big Sky Conference:
Reese Betschart - Eastern Washington University - OH/DS (Front Range)
Zola Zuccolo - University of Idaho - Setter/OPP (Athena Volleyball Academy)
Brooke Christoffersen - Idaho State University - OPP/Setter (Club V)
Kaylee Paulson - University of Montana - OH (CPA)
Brooklyn Pierce - University of Montana - MB
Isa Taylor - University of Montana - OH (Club V)
Elli Esko - Montana State University - OH (Apex)
McKenna Kimbell - Montana State University - MB (Sunshine)
Taylor McDonald - Montana State University - MB/OH (Shockwave)
Kate Federico - Northern Arizona University - Libero/DS (Arizona Sky)
Avalon Legg - Northern Arizona University - Libero/DS (East Valley Juniors)
Mallory Reynolds - Northern Arizona University - Setter (International: Canada)
Jenna Baller - University of Northern Colorado - Libero/DS (Elevation)
Kaitlyn Hutchins - University of Northern Colorado - OH (Roots)
Jaylyn Lynch - University of Northern Colorado - Libero/DS (Colorado Skyline)
Addison Roark - University of Northern Colorado - MB/OPP (NORCO)
Riley Taylor - University of Northern Colorado - OPP/OH (Triangle)
Gillian Walton - University of Northern Colorado - OH/OPP (MAVS KC)
Katelyn Davey - Portland State University - OPP (Arizona Sky)
Maryn Hall - Portland State University - OH (OMNI)
Xanthe Ocampo - Portland State University - Libero/DS (OMNI)
Talea Barry - Southern Utah University - Setter/DS (Balboa Bay)
Ella Robbins - Utah Tech University - MB (South County VBC)
Ashlyn Aaron - Weber State University - OPP (CPA)
Addie Beck - Weber State University - OH (Club V)
Lexie Carlson - Weber State University - OH (Club V)
Maris Mauzey - Weber State University - OPP (Aspire)
Sophia Sparrow - Weber State University - MB (Mountain Peak)
Reagan Williams - Weber State University - Libero/DS (Club V)

Big South Conference:
Jenna Kitchens - Charleston Southern University - OH (NKYVC)
Brynn Minter - Charleston Southern University - OH (SC Rockstar)
Ava Pitzer - Charleston Southern University - OH (River Valley Juniors)
Adeline Wieler - Charleston Southern University - Libero/DS (A5)
Aubrey Jordan - Gardner-Webb University - OH/OPP (Triangle)
Parker LaFontaine - Gardner-Webb University - MB/OPP (Vegas Aces)
Gracyn Sanders - Gardner-Webb University - MB (Top Flight)
Peyton Slone - Gardner-Webb University - OH/OPP (OTVA)
Kiera Vazquez - Gardner-Webb University - DS/OH (Winter Park)
Kinnady Boothe - High Point University - OH (Piedmont)
Alden Schwartz - High Point University - OPP/MB (Carolina Union)
Eliana Whittaker - High Point University - Setter/DS (Carolina Union)
Elise Jensen - University of North Carolina Asheville - Setter (IMG Academy)
Leah Okogbenin - University of North Carolina Asheville - MB (Carolina Juniors)
Kaylie Bourn - Presbyterian College - MB (STVA)
Sophia Pheney - Presbyterian College - Setter (SC Elite)
Sophia Verdicchio - Presbyterian College - Libero/DS (East Carolina Juniors)
Mia Jannazzo - Radford University - OH/DS (Milwaukee Sting)
Hannah Nicholson - Radford University - Libero/DS (A5)
Macie Potter - Radford University - OH (Excel)
Ela Shepherd - Radford University - Setter/OPP (River Valley Juniors)
Rose Whitemountain - Radford University - Libero/DS (High Performance STL)
Tehillah Garrison - University of South Carolina Upstate - OH (Top Select)
Emerson Spiesz - University of South Carolina Upstate - Libero/DS (AVC)
Sophie Spivey - University of South Carolina Upstate - OPP (Game Point)
Maggie Czajka - Winthrop University - MB (Milwaukee Sting)
Morgan Heater - Winthrop University - Setter (NKYVC)
Reese Kincaid - Winthrop University - OH (Athena Volleyball Academy)
Lindsay Langner - Winthrop University - Libero/DS (Kairos Elite)

Big Ten Conference:
Brooke Harwood - University of California, Los Angeles - MB (AZ Storm)
Vivian Hickman - University of California, Los Angeles - Setter (Arizona Sky)
Presley Thompson - University of California, Los Angeles - Libero/DS (WAVE)
Maya Harris - University of Illinois - OH (Munciana)
Madi Miles - University of Illinois - OH (Boiler Juniors)
Ellie Hepler - Indiana University - Libero/DS (Boiler Juniors)
Mallory Matheny - Indiana University - Setter (Mintonette)
Sara Snowbarger - Indiana University - OH (Mintonette)
Nikolija Bulatovic - University of Iowa - Setter (1st Alliance)
Henlee Moszkowicz - University of Iowa - Libero/DS (Houston Skyline)
Brooklynne Brass - University of Maryland - OH (Sports Performance)
Ava Brown - University of Maryland - OPP (Mintonette)
Raina Chwialkowski - University of Maryland - Libero/DS (Sanford Sports)
Elayna Davidson - University of Maryland - Libero/DS (Sports Performance)
Marlee Sivak - University of Maryland - OH (Milwaukee Sting)
Kapri Garnett - University of Michigan - OPP (Sunshine)
Megan Ingersoll - University of Michigan - OH (Alabama Performance)
Jaden Jones - University of Michigan - MB (OTVA)
Meredith Martin - University of Michigan - Libero/DS (Legacy)
Madi Andrews - Michigan State University - OH (Athena Volleyball Academy)
Colbie McKenna - Michigan State University - OH (East Coast Power)
Alana Whitfield - Michigan State University - Libero/DS (Illini Elite)
Makenna Crosson - University of Minnesota - OH (Vision)
Elena Hoecke - University of Minnesota - MB (Minnesota Select)
Madi Kraft - University of Minnesota - Libero/DS (Northern Lights)
Gabby DiVita - University of Nebraska - OH (Legacy)
Jayden Robinson - University of Nebraska - OH/OPP (Houston Skyline)
Keoni Williams - University of Nebraska - MB (Dallas Skyline)
Kaitlyn Bodnar - Northwestern University - Setter (VCNebraska)
Simone Huarte - Northwestern University - OH (OMNI)
Hayley Schaaf - Northwestern University - MB (Athena Volleyball Academy)
Clara Schramm - Northwestern University - OH (Arizona Sky)
Ellie Stiernagle - Northwestern University - Setter (Sports Performance)
Maya Stillwell - Northwestern University - MB (SC Rockstar)
Layla Hoying - Ohio State University - OH (Mintonette)
Jolian Miller - Ohio State University - MB (Alabama Performance)
Bailey Nakanelua - Ohio State University - Setter (Ku'ikahi)
Alia Schoonover - Ohio State University - MB (Mintonette)
Laura Eichert - University of Oregon - OH (North Pacific Juniors)
Marlena Garcia - University of Oregon - Setter (USANY)
Alaina Pollard - University of Oregon - MB (1st Alliance)
Lizzy Robinson - University of Oregon - Libero/DS (Tribe)
Haley Burgdorf - Pennsylvania State University - OH (Sports Performance)
Kendall Northern - Pennsylvania State University - MB (Elevation)
Finley Krystkowiak - Pennsylvania State University - OH (WAVE)
Danielle Whitmire - Pennsylvania State University - Setter (TAV)
Lily Bosworth - Purdue University - MB (Illini Elite)
Elle Schara - Purdue University - Libero/DS (1st Alliance)
MaryKate Scheumann - Purdue University - Libero/DS (Team Pineapple)
Sydni Vice - Purdue University - OH/OPP (Memphis Juniors)
Brooke Baldwin - Rutgers University - Setter (Milwaukee Sting)
Kami Dyrstad - Rutgers University - Libero/DS (Premier Nebraska)
Malia Romes - Rutgers University - MB (Athlete HQ)
Addison Coady - University of Southern California - MB (Mizuno Long Beach)
Taliyah Hanks - University of Southern California - MB (Dead Frog)
Riley Malloy - University of Southern California - OH (Austin Skyline)
Milly McGee - University of Southern California - Setter (SCVC)
Layli Ostovar - University of Southern California - OH (Mizuno Long Beach)
Lily Mae Burkle - University of Washington - Setter (North Pacific Juniors)
Hayden Conner - University of Washington - MB (AZ Storm)
Sammy Destler - University of Washington - OH (SCVC)
Kylie Kleckner - University of Washington - OH (TAV)
Kaitlyn Nguyen - University of Washington - Libero/DS (Sudden Impact)
Rian Stephan - University of Washington - OH (Apex NW)
Audrey Flanagan - University of Wisconsin - OH (SC Rockstar)
Kymora Scott - University of Wisconsin - MB/OPP (Xtreme Performance)
Lynney Tarnow - University of Wisconsin - MB (1st Alliance)
Halle Thompson - University of Wisconsin - OH (Houston Skyline)

Big West Conference:
Samantha Bailey - California Baptist University - OPP (Tsunami)
Nalanie Neal - California Baptist University - OH/MB/OPP (River Valley Juniors)
Ifeoma Okeke - California Baptist University - MB (SC Rockstar)
Taylor Boice - University of California, Irvine - MB (SCVC)
Memphis Burnett - University of California, Irvine - OH/OPP (TStreet)
Kaia Ciszewski - University of California, Irvine - OH/DS (Mizuno Long Beach)
Vani Tatoulian - University of California, Irvine - MB (City)
Tatawan Vongfak - University of California, Irvine - Libero/DS (SG Elite)
Casi Doll - University of California, Riverside - OH (TStreet)
Mckenna Giles - University of California, Riverside - Libero/DS (Pipeline)
Mahala Huntsman - University of California, Riverside - Setter/OPP (Winter Park)
Alba Canko - University of California, San Diego - Setter (Coast)
Lydia Fisher - University of California, San Diego - OPP (A5)
Bridget Blu - California Polytechnic State University - OH (Mizuno Long Beach)
Teagan Cooling - California Polytechnic State University - MB/OPP (Vision)
Kamille Scott - California Polytechnic State University - OPP (AZ Storm)
Noe Vanacht - California Polytechnic State University - Libero/DS (Vision)
Samantha Capinpin - California State University, Bakersfield - Setter (Forza1 North)
Leylah Duran - California State University, Bakersfield - MB (Arizona Sky)
Sibley Oster - California State University, Fullerton - Setter (Austin Skyline)
Bella Risling - California State University, Fullerton - OH/OPP (Top Flight)
Parys Taylor - California State University, Fullerton - OH (LAVA North)
Kyler Birkelbach - California State University, Long Beach - MB (TAV)
Emma Gardner - California State University, Long Beach - OH/OPP (Metro)
Ashton Nelson - California State University, Long Beach - OH (A4)
Annie Gilmore - California State University, Northridge - OH (A4)
Madison Jameson-Rodriguez - California State University, Northridge - MB (Vegas United)
Nikola Gamlin - California State University, Sacramento - MB (International: Canada)
Mia Molnar - California State University, Sacramento - OH (International: Canada)
Addy Scheitlin - California State University, Sacramento - OH (SynergyForce)
Bree Carson - Utah Valley University - OH (A4)
London Armstrong - Utah Valley University - OH/OPP (Idaho Crush)
Chloe Hansen - Utah Valley University - OH (Idaho Crush)
Brighton Richards - Utah Valley University - Libero/DS (Viper)

Coastal Athletic Association (CAA):
Ava Bassett - Campbell University - MB (Tsunami)
Tess DeZurik - Campbell University - Libero/DS (NC Volleyball Academy)
Aubree Fernandez - Campbell University - Libero/DS (TAV)
Alexis Jodie - Campbell University - Setter (Carolina Rogue)
Marlena Lee - Campbell University - MB (Carolina Rogue)
Cayla Prohaska - Campbell University - OH (1st Alliance)
Lucy Haywood - College of Charleston - MB (Tennessee Performance)
Maddie Hewitson - College of Charleston - OPP (Ocala Power)
Julianna Nzambele - College of Charleston - OH (Carolina Union)
Violet Poole - College of Charleston - Libero/DS (SC Elite)
Cecilia Christy - Elon University - MB (3dge)
Camryn Kanell - Elon University - MB (Tribe)
Caroline Smith - Elon University - OH (Piedmont)
Olivia Bryant - Hampton University - OPP (Coast)
Morgan Reeves - Hampton University - OH (Paramount)
Dawn Pena - Hofstra University - OPP/MB/OH (Masters Volleyball Academy)
Madi Curry - North Carolina A&T State University - OH (A5 Gwinnett)
Eden Eyassu - North Carolina A&T State University - Libero/DS (Sports Performance)
Kamryn Jackson - North Carolina A&T State University - OH/OPP (Oklahoma Peak)
Kirsten Kemper - North Carolina A&T State University - Setter/OPP (NKYVC)
Aberdeen Callaway - Northeastern University - OH (Actyve)
Cayenne Ceman - Northeastern University - OH (Mizuno Long Beach)
Kate Ewing - Northeastern University - MB (Northeast)
Quinn Hickman - Northeastern University - OPP/OH (Houston Skyline)
Bryce Leatherwood - Northeastern University - MB (Coast)
Lily Goyer - University of North Carolina Wilmington - MB (1st Alliance)
Annie Harney - University of North Carolina Wilmington - Libero/DS (Tennessee Performance)
Addi Vaughn - University of North Carolina Wilmington - Setter (MAVA)
Avari Amstutz - Stony Brook University - OH (Rock City)
Taryn Su - Stony Brook University - Setter/DS (Metro)
Nola Duncan - Towson University - OH (Top Tier)
Kamree Orizotti - Towson University - Setter (Athena Volleyball Academy)
Kayla Zanon - Towson University - Libero/DS (Miami Hype)
Regan Hill - College of William & Mary - OPP/DS (East Coast Power)
Emily McKee - College of William & Mary - OH/DS (Northeast)
Teagan Pocius - College of William & Mary - MB (Rockwood Thunder)

Conference USA:
Avery Brown - University of Delaware - Setter/OPP (Texas Tornados)
Sofia Guerrero-Wilson - University of Delaware - MB/OPP (A5)
Auna Wiegand - University of Delaware - MB/OH (1United)
Emily Zgonc - University of Delaware - Libero/DS (Milwaukee Sting)
Gina Fedrigo - Florida International University - OPP (Legacy)
Morgan Sears - Florida International University - MB/OH (Pohaku)
Reesa Zimmerman - Florida International University - MB/OPP (Elevation)
Millie Burgess - Jacksonville State University - OH/MB (Bama Elite)
Anna Fish - Jacksonville State University - OH (KIVA)
Anna Ray - Jacksonville State University - MB (Rhythm Volleyball Academy)
Madelyn Lincicum - Kennesaw State University - MB (Academy)
Anna Ofenheusle - Kennesaw State University - OH (Alliance)
Alexis Sowers - Kennesaw State University - Libero/DS (Jacksonville Juniors)
Ashley Theiss - Kennesaw State University - OH (High Performance STL)
Natalie Langston - Liberty University - OH/OPP (NC Volleyball Academy)
Keira Rosenmarkle - Liberty University - OH/OPP (CHAVC)
Jana Thymes - Liberty University - OH/MB/OPP (Cajun Elite)
Mia Duong - Louisiana Tech University - Libero/DS (Corpus Christi Force)
Jenna Hehman - Louisiana Tech University - OH (Austin Performance)
Tyra McKinnie - Louisiana Tech University - MB (Oklahoma Peak)
Violet Morrandez - Louisiana Tech University - MB/OPP (Colorado Skyline)
Kaycee Pennie - Louisiana Tech University - MB (Absolute Volleyball Academy)
Kylie Rodriguez - Louisiana Tech University - OH/OPP (Dallas Skyline)
Abbi Sells - Louisiana Tech University - Libero/DS (Legacy)
Taylor Woods - Louisiana Tech University - OH/OPP (TAV)
Addison Burks - Middle Tennessee State University - Libero/DS (Rhythm Volleyball Academy)
Kailyn Connelly - Middle Tennessee State University - MB (SKY Elite)
Marianne Garcia - Middle Tennessee State University - Libero/DS (Arizona Sky)
Jaslyn Reed - Middle Tennessee State University - OH/OPP (North Pacific Juniors)
Madison Wehr - Middle Tennessee State University - Setter (Game Point)
Brielle Gengelbach - Missouri State University - MB (MAVS KC)
Hallie Rillie - Missouri State University - Setter (Sports Academy)
Avery Sands - Missouri State University - Libero/DS (Dynasty)
Ava Archibald - New Mexico State University - OH/OPP (Revolution Volleyball Academy)
Paige Nelson - New Mexico State University - Setter (Absolute)
Emmy Nicholas - New Mexico State University - Libero/DS (Houston Juniors)
Sadie Ross - New Mexico State University - OH (North Pacific Juniors)
Lilliana Saldivar - New Mexico State University - OH (SynergyForce)
Sarah Odell - Sam Houston State University - OH (North Houston Elite)
Laila Amos - University of Texas at El Paso - OH (A5)
Caryme Molina - University of Texas at El Paso - Setter (Houston Stellar)
Kaylynn Pardue - University of Texas at El Paso - MB (Colorado Juniors)
Elizabeth Pickett - University of Texas at El Paso - OH (TAV)
Daisy Voskuhl - University of Texas at El Paso - OH (Houston Skyline)
Bella Widmer - University of Texas at El Paso - Libero/DS (Boiler Juniors)
Calista Foster - Western Kentucky University - Libero/DS (Boiler Juniors)
Eliza McKnight - Western Kentucky University - MB (Alliance)

Horizon League:
Alyssa Cerovac - Cleveland State University - OH (International: Canada)
Audrey Ellis - Cleveland State University - OH/OPP (AVC)
Addison Koppelman - Cleveland State University - OH (RockCity)
Morgan Begley - Indiana University Indianapolis - Libero/DS (1st Alliance)
Bailey Sinish - Indiana University Indianapolis - OH (Summit VBC)
Lauren White - Indiana University Indianapolis - Setter (Tri-State Elite)
Lilly Abney - Northern Illinois University - OH/DS (Circle City)
Charlotte Gramzow - Northern Illinois University - Libero/DS (Michigan Elite)
Katie Pahl - Northern Illinois University - OH/OPP (Toledo VBC)
Emma Adkins - Northern Kentucky University - Setter/OH (Tri-State Elite)
Emily Erwin - Northern Kentucky University - OPP/Setter (Lexington United)
Liv Hosford - Oakland University - OH (Rise Volleyball Academy)
Kamsi Iweajunwa - Oakland University - MB (FaR Out)
Maddie Jipping - Oakland University - OPP (FaR Out)
Morgin Parsley - Oakland University - Setter (Legacy)
Kate Vrabel - Oakland University - Libero/DS (Circle City)
Ellie Adams - Purdue University Fort Wayne - OH/DS (NIVA)
Anna Cassidy - Purdue University Fort Wayne - MB (RockCity)
Alyssa Gumbel - Purdue University Fort Wayne - OH (Team Pineapple)
Kenlee Barnard - Robert Morris University - Setter (Team Indiana)
Bri Blair - Robert Morris University - MB (Premier Academy)
Lauren Decker - Robert Morris University - OH (NOVA)
Caroline Hanner - Robert Morris University - OH/OPP (Elite Sports Ohio)
Maddie Siphakongviseth - Robert Morris University - Libero/DS (VolleyFX)
Ambryn Aanonsen - University of Wisconsin-Green Bay - OPP/MB (Milwaukee Sting)
Victoria Kurilov - University of Wisconsin-Green Bay - MB (Minnesota Select)
Sari Marks - University of Wisconsin-Green Bay - Setter/OPP (Sting United)
Riley Schmitz - University of Wisconsin-Green Bay - Libero/DS (FC Elite)
Eva Swenson - University of Wisconsin-Green Bay - Setter (Minnesota Select)
Olivia Doerre - University of Wisconsin-Milwaukee - Libero/DS (Kokoro)
Emma Duffy - University of Wisconsin-Milwaukee - Setter (FaR Out)
Kayla Landerud - University of Wisconsin-Milwaukee - MB/OPP (Sting United)
Hope Wagner - University of Wisconsin-Milwaukee - OH (Chi City)
Ali Hayes - Wright State University - OH (Mintonette)
Khalia Lawrence - Wright State University - MB (Elite VBTC)
Abbey Knight - Wright State University - OPP/OH (Sports Performance)
Korina Barber - Youngstown State University - OPP/MB (Mintonette)
Natalie Carr - Youngstown State University - OH (Pittsburgh Elite)
Journey Nicola - Youngstown State University - Libero/DS (Mintonette)
Hayden Rodriguez - Youngstown State University - Setter (Toledo VBC)

Ivy League (committed to the application process):
Sophie Haskell - Brown University - Libero/DS (Austin Skyline)
Elle Holley - Brown University - OH (Madfrog)
Frankie Jones - Brown University - MB (Sunshine)
Ramsey Larke Chastain - Brown University - Setter (Stars Sports)
Lawson Monroe - Brown University - MB (A5)
Megan Phan - Brown University - Setter (VA Juniors)
Morgan Sanders - Brown University - OPP (A5)
Elise Hiemstra - Columbia University - OH/OPP (Legacy)
Claire Mo - Columbia University - Setter (Metro)
Danica Nordlicht - Columbia University - MB (WAVE)
Dahlia Roberts - Columbia University - OPP (IMG Academy)
Charlotte Nowak - Cornell University - OH (WAVE)
Kiran Rio - Cornell University - OH/OPP (Houston Juniors)
Ellery Williamson - Cornell University - OH/OPP (International: Canada)
Sloan Balsley - Dartmouth College - OH (A5)
Jaida Cekic - Dartmouth College - OH/OPP (Downstate Juniors)
Audrey Kalorin - Dartmouth College - Setter/OPP (NC Volleyball Academy)
Clementine Tebbe - Dartmouth College - MB (NYC Juniors)
Kayla Nwabueze - Harvard University - MB (Legacy)
Masina Ogbechie - Harvard University - OPP (Sports Academy)
Catlin Shao - Harvard University - Setter (MAVS KC)
Jordan Shelor - Harvard University - Libero/DS (Mizuno Long Beach)
Skylar Greene - University of Pennsylvania - OH (1st Alliance)
Pilar Kelley - University of Pennsylvania - OPP (Absolute)
Stella Kennedy - University of Pennsylvania - OH (Sunshine)
Lauryn Lewis - University of Pennsylvania - MB (Sunshine)
Reese Stringer - University of Pennsylvania - Setter (Mizuno Long Beach)
Ava Wang - University of Pennsylvania - Libero/DS (Vision)
Natalie Surges - Princeton University - OH (1st Alliance)
Allison Tredwell - Princeton University - Setter (TAV)
Hailie Vaughn - Princeton University - OH (Pohaku)
Callie Funk - Yale University - MB (Houston Juniors)
Caroline Huseman - Yale University - OH (TAV)
Skylar Jackson - Yale University - OH (Dallas Skyline)
Kalyssa Taggart -  Yale University -  Setter/OPP (OTVA)

Metro Atlantic Athletic Conference (MAAC):
Hanna Rider - Canisius University - Libero/DS (Alliance)
Kenslie Warmbrodt - Canisius University - Setter (Northern Nevada Juniors)
Mary Kate Bradley - Fairfield University - Setter (Sky High)
Lilly Guinane - Fairfield University - Libero/DS (A4)
Keyaira Limuel-Washington - Fairfield University - MB (Austin Juniors)
Noella Migliuri - Fairfield University - Setter (CPA)
Aislin Oldach - Fairfield University - OH (Front Range)
Courtney Vines - Fairfield University - MB (All Star Empire)
Anissa Cooper - Iona University - MB (WAVE)
Grace Daniels - Iona University - Setter (RockCity)
Karsyn Harris - Manhattan University - OH (East Valley Juniors)
Margaret O'Brien - Manhattan University - OH (VC United)
Emily Ernst - Marist College - Setter (Sky High)
Molly Malone - Marist College - MB/OPP (Toledo VBC)
Tami Afolalu - Merrimack College - OH/OPP (Husky Volleyball Club)
Kadee Goolsby - Niagara University - OPP (Mintonette)
Sophia Gisslen - Quinnipiac University - Setter (Team Pineapple)
Olivia De Saro - Rider University - DS/OH (Synergy)
Maisie Nawrocki - Rider University - OH (RockCity)
Sofia Hechavarria - Sacred Heart University - OH (USANY)
Mia Miller - Sacred Heart University - OPP/OH (IMG Academy)
Audrey Schabes - Sacred Heart University - Setter (Adversity)

Mid-American Conference (MAC):
Taylor Donovan - University of Akron - Libero/DS (Circle City)
Lucy McCollum - Ball State University - Setter (Ignite Elite)
Leah Pike - Ball State University - MB (Toledo Volleyball Club)
Mallory Pike - Ball State University - OH (Toledo Volleyball Club)
Merritt Sliwa - Ball State University - OH (Rev Volleyball Academy)
Ania Magier - Bowling Green State University - MB (International: Canada)
Makiaya Turner - Bowling Green State University - OH/OPP (Mintonette)
Haley Wilson - Bowling Green State University - OPP (AVC)
Abisola Adebayo - University at Buffalo - MB (Houston Skyline)
Angelina Siepierski - University at Buffalo - OH (CADO)
Audrey Hackney - Central Michigan University - Setter (Rockwood Thunder)
Lily Jones - Central Michigan University - OH/OPP (Circle City)
Addi Samolinski - Central Michigan University - Libero/DS (1st Alliance)
Brenna Storz - Central Michigan University - MB (The Academy)
Meisha Sykes - Central Michigan University - MB (Paramount)
Mya Eberlein - Eastern Michigan University - MB (NIVA)
Lina Govoni - Eastern Michigan University - Setter (Sports Performance)
Maddie Herman - Eastern Michigan University - MB (The Academy)
Kayla Ostrander - Eastern Michigan University - Libero/DS (Legacy)
Nattie Slusher - Eastern Michigan University - OH (Tri-State Elite)
Olivia Stewart - Eastern Michigan University - MB (Sports Performance)
Haley Trosky - Eastern Michigan University - OPP (Pittsburgh Elite)
Kendall Bosse - Miami University - MB (Tri-State Elite)
Madison Brown - Miami University - Setter (The Academy)
Ria Furuta - Miami University - Libero/DS (NKYVC)
Rachel Morgan - Miami University - Libero/DS (Elevation)
Sophia Stallworth - Miami University - OH/OPP (Top Select)
Reesa Zimmerman - Miami University - OH (Elevation)
Rowan Kelly - Ohio University - Setter (NOVA)
Rose Mahin - Ohio University - OH (Rev Volleyball Academy)
Trixie Carroll - Central Michigan University - OH (VC United)
Audrey Dyas - University of Toledo - MB (NKYVC)
Jadyn Kennedy - University of Toledo - Libero/DS (Legacy)
Lucy Monahan - University of Toledo - MB (Michigan Elite)
Ella Askin - Western Michigan University - OH (KIVA)

Mid-Eastern Athletic Conference:
Karina Diaz - Coppin State University - Libero/DS (Puerto Rico)
Haley Holbert - Coppin State University - Setter (Triangle)
Riley Parker - Delaware State University - Setter (Carolina Chaos)
Addison Buckner - Howard University - OH (Milwaukee Sting)
Haara Umenwaliri - Howard University - MB (Triangle)
Lauryn Wiley - Howard University - Libero/DS (Houston Skyline)
Bailey Swinton - Morgan State University - Libero/DS (VA Juniors)
Alaina Walker - Morgan State University - Setter/OPP (Carolina Rogue)
Amari Chaney - Norfolk State University - Setter/DS (Club 757)
Lusi Damuni - North Carolina Central University - Setter (Mountain Peak)
Jayla Egerton - North Carolina Central University - Libero/DS (Triangle)
Breylan Fairley - North Carolina Central University - Setter/DS (Top Select)
Isabella Rodriguez - North Carolina Central University - Libero/DS (Game Point)
Amani Hawkins - South Carolina State University - OH/DS (Untouchables EPA)

Missouri Valley Conference:
Sydnee Nelson - Belmont University - OH (FC Elite)
Hayden Booth - Bradley University - Setter (Premier Nebraska)
Ella Nigl - Bradley University - OH/OPP (FC Elite)
Maren Ouellette - Bradley University - OH (Iowa Rockets)
Kamryn Behrns - Drake University - OPP (VCNebraska)
Isabelle Kremer - Drake University - OH/OPP (Iowa Rockets)
Hailey Laffond - Drake University - MB (Vital)
Ava Turlais - Drake University - MB (Wisconsin Juniors)
Avery Vogt - Drake University - Setter (Iowa PowerPlex)
Aubry Dowling - University of Evansville - Libero/DS (Rev Volleyball Academy)
Wren Jones - University of Evansville - OH (EVA)
Carsyn Kelley - University of Evansville - Setter (Iowa Select)
Ellie Burr - Illinois State University - Libero/DS (Coast)
Jillian Ferrill - Illinois State University - OH (Legacy)
Ella Kohnen - Illinois State University - Setter (Milwaukee Sting)
Alaina Kraemer - Illinois State University - OPP (Madtown)
Sidney Wright - Illinois State University - MB (Chi City)
Kennedy Glasgow - Indiana State University - Libero/DS (Pohaku)
Dylann Loggins - Indiana State University - MB (Paramount)
Maezi Snyder - Murray State University - MB/OPP (Boiler Juniors)
Maggie Michaels - University of Northern Iowa - Libero/DS (Illini Elite)
Claire Munch - University of Northern Iowa - MB/OH (MVP)
Alex Arrington - Southern Illinois University Carbondale - Setter/MB (CTV)
Bella Del Real - Southern Illinois University Carbondale - Libero/DS (1st Alliance)
Kenzie Moeller - Southern Illinois University Carbondale - OH (Iowa Select)
Natalie Vance - Southern Illinois University Carbondale - OH (Team Indiana)
Kyla Bellich - Valparaiso University - MB (VC United)
Rylee Bumgardner - Valparaiso University - Libero/DS (Circle City)
Mia McCall - Valparaiso University - Setter/OPP (Chi City)
Sarah Pippin - Valparaiso University - OH (NIVA)
Maddie Steele - Valparaiso University - MB/OPP (NKYVC)

Mountain West Conference:
Gianna Bogan - University of California, Davis - OH/OPP (SynergyForce)
Jada Johnson - University of California, Davis - OH/OPP (North Pacific Juniors)
Ana Stojanovic - University of California, Davis - OH/OPP (International: Canada)
Isabella Umpierre - University of California, Davis - OPP (Winter Park)
Khloe Wong - University of California, Davis - Libero/DS (SynergyForce)
Alayna Austin - Grand Canyon University - Libero/DS (Aspire)
Audrey Cook - Grand Canyon University - Setter (Houston Juniors)
Kaela Jenkins - Grand Canyon University - MB (Mintonette)
Gentry Oblad - Grand Canyon University - OH (Vegas Aces)
Addison Wiemann - Grand Canyon University - OH/OPP (AZ Storm)
Cameron Holcomb - University of Hawaii - Libero/DS (WAVE)
Rachel Purser - University of Hawaii - MB (Vegas Aces)
Julie Beckham - University of Nevada, Las Vegas - OH (Top Flight)
Arrie Brown - University of Nevada, Las Vegas - OH (Tulsa Performance)
Natalie Monroe - University of Nevada, Las Vegas - OH (Vision)
Karly Bonaventure - University of Nevada, Reno - MB (NorCal)
Madi Long - University of Nevada, Reno - OPP (Northern Nevada Juniors)
Campbell Hollister - University of New Mexico - MB (Revolution Volleyball Academy)
Viena Moliis - University of New Mexico - OH/OPP (International: Finland/Canada)
Florence Campeau - San Jose State University - Setter (International: Canada)
Cayleigh Cervenka - United States Air Force Academy - MB (Alamo)
Aylani Correa - United States Air Force Academy - Libero/DS (Gamepoint)
Emerson Jones - United States Air Force Academy - MB/OPP (Excel)
Neely Leathers - United States Air Force Academy - Setter (KC Power)
Deylen Mendivil - United States Air Force Academy - OH (Alamo)
Jenness Orcutt - United States Air Force Academy - OPP/OH (Game Point)
Kennedy Simon - United States Air Force Academy - OH/MB (Dallas Skyline)
Rylee Heinz - University of Wyoming - MB (Temecula Viper)
Ruby Jensen - University of Wyoming - MB (Revolution Volleyball Academy)
Emerson Macias - University of Wyoming - OH (Temecula Viper)

Northeast Conference (NEC):
Hanley Schmidt - Central Connecticut State University - OH (Iowa Select)
Ashlyn Gualtieri - Fairleigh Dickinson University - OH (DVA)
Katie Barbour - Le Moyne College - Setter/OPP (Triangle)
Taliah Benson - Le Moyne College - OH (MoCo MAVS)
Avery Stromberg - Le Moyne College - OH (Synergy)
Camryn Harris - University of New Haven - Libero/DS (Elevation)
Quinn Yenshaw - University of New Haven - OH (FaR Out)
Jayla Zayti - University of New Haven - MB (Legacy)
Roe Beland - Stonehill College - OH/MB (603 United)
Mia Crowley - Stonehill College - OH/OPP (TAV Houston)
Kasia Dowd - Stonehill College - OH/OPP (Colorado Juniors)
Jordan Valentine - Stonehill College - OH/DS (Arete)

Ohio Valley Conference (OVC):
Kyla Coolman - Eastern Illinois University - Setter (Team Pineapple High Performance)
Addison Erb - Eastern Illinois University - MB (VC United)
Kaeden Foxx - Eastern Illinois University - OH (Sharks VBC)
Emma Hanson - Eastern Illinois University - MB (Mizuno M1)
McKenna Morton - Eastern Illinois University - OH/DS (Drive Nation)
Mirea Thederahn - Eastern Illinois University - OH/OPP (Montverde)
Valyn Donahoo - Lindenwood University - OH (OK Charge)
Lauren Ortwerth - Lindenwood University - OH (High Performance STL)
Reagan Baxter - Morehead State University - MB (Union)
Norah Campbell - Morehead State University - Libero/DS (MAVA)
Haidyn Carter - Morehead State University - MB (KIVA)
Josie Certa - Morehead State University - Setter (Illini Elite)
Jasmine Daniels - Morehead State University - Setter (Rev Volleyball Academy)
Mary Rindler - Morehead State University - OH (Grandlake)
Anna Schiltz - Morehead State University - MB (Top Flight)
Ella Warrick - Morehead State University - OH (Circle City)
Ava Mathews - Southeast Missouri State University - OPP (High Performance STL)
Sydney Miller - Southeast Missouri State University - MB (Pursuit)
Brooklyn Ritter - Southeast Missouri State University - Setter (1st Alliance)
Paige Smith - Southeast Missouri State University - OPP (Untouchables EPA)
Georgia Bresnahan - Southern Illinois University Edwardsville - OH (The Academy)
Charlotte Dudik - Southern Illinois University Edwardsville - OPP/OH (The Academy)
Mackenzie Higgins - Southern Illinois University Edwardsville - Libero/DS (Elevation)
Ashlyn Schulze - Southern Illinois University Edwardsville - MB (Kokoro)
Aubrey Fair - University of Southern Indiana - OH (Illini Elite)
Vita Sensenbrenner - University of Southern Indiana - MB/OH (Union)
Amani Agoot - Tennessee Technological University - MB (Michigan Elite)
Kamya Mahorn - Tennessee Technological University - OH/DS (KIVA)
Morgan Petelin - Tennessee Technological University - Setter/OPP (Illini Elite)
Bella Potempa - Tennessee Technological University - OH (Adversity)

Pac-12 Conference:
Jenelle Legates - Boise State University - Setter (Vision)
Savannah Sheridan - Boise State University - OH (BRUSA)
Sadie Snyder - Boise State University - OH (Revolution Volleyball Academy)
Azlynn Tittmann - Boise State University - OH/DS (ARVC)
Kiley Devery - California State University, Fresno - OPP (Iowa Rockets)
Brooke Jenkins - California State University, Fresno - OH (Arizona Sky)
Olivia Ewing - Colorado State University - MB (NORCO)
Hayden Grimes - Colorado State University - Libero/DS (Fight Club)
Abby Little - Colorado State University - OH/OPP (Big Sky)
Jaedyn Riley - Colorado State University - Setter (NorCal)
Ella Stowell - Colorado State University - OH (KC Power)
Isabel Bertelsen - Oregon State University - Libero/DS (Winter Park)
Abby Lesagonicz - Oregon State University - OH (Coast)
Layla Austin - San Diego State University - OH (TAV)
Logan Cary - San Diego State University - Setter/OPP (Front Range)
Chelsea Cocks - San Diego State University - MB (International: Australia)
Karis Carpenter - Texas State University - Libero/DS (STVA)
Emma Elsasser - Texas State University - MB/OPP (Houston Juniors)
Izzy Scholvin - Texas State University - Setter (Mintonette)
AC Gibbs - Utah State University - Libero/DS (TAV Houston)
Taytum Nelson - Utah State University - MB (Elevate Athletics)
Madi Rich - Utah State University - OPP/OH (Club V)
Whitney Dewicki - Washington State University - OH (Colorado Juniors)

Patriot League:
Sydney Guerrier - American University - Setter/OPP (Jupiter Elite)
Samantha McMillan - American University - OH (Wildfire Volleyball Academy)
Gabbie Vizek - American University - MB (Metro)
Emerson Boyd - Bucknell University - Setter/OPP (Arete)
Isabella Charlton - Bucknell University - Libero/DS (Mobile Storm)
Marion Haskell - Bucknell University - OH/OPP (NASA)
Emerson Springs - Bucknell University - OH (East Coast Power)
Gabby Emch - Colgate University - Libero/DS (A5)
Charlotte Goldfeder - Colgate University - OPP (VolleyFX)
Reagan Knipling - Colgate University - Setter/OPP (Houston Juniors)
Nora Benjamins - College of the Holy Cross - MB (1st Alliance)
Drew Flanagan - College of the Holy Cross - Setter (Aspire)
Grace Jamison - Lafayette College - OH (Actyve)
Paighton Erb - Lehigh University - MB (Premier Nebraska)
Lia Henderson - Lehigh University - OPP/OH (East Coast Power)
Summer Hodge - Lehigh University - Libero/DS (Excel)
Natalie Unkrich - Lehigh University - OH/OPP (Carolina Union)
Makenzie Wingett - Lehigh University - MB/OPP (Nebraska Elite)
Elise Bocanegra - Loyola University Maryland - Libero/DS (1st Alliance)
Regan Haverstock - Loyola University Maryland - Setter (NC Volleyball Academy)
Abby Kim - Loyola University Maryland - OH (Sideout Sports)
Lillian Dempkey - United States Military Academy - Setter (VC United)
Liliana Fox - United States Military Academy - OH (VC United)
Reyna Jones - United States Military Academy - MB (Revolution Volleyball Academy)
Marley Lightsey - United States Military Academy - OH (Alamo)
Chava Nuckols - United States Military Academy - OPP (Drive Nation)
Ally Orth - United States Military Academy - Setter (Shockwave)
Caroline Adams - United States Naval Academy - Setter (Absolute Volleyball Academy)
Brianna Bowman - United States Naval Academy - OH/DS (SC Elite)
Hailey Jacobus - United States Naval Academy - OH/OPP (Madfrog)
Simone Lawson - United States Naval Academy - OPP/Setter (Richmond Volleyball Academy)
Avery Maddux - United States Naval Academy - MB (Adversity)
Mackenzie Palumbo - United States Naval Academy - OPP/OH (Mintonette)
Izzy Picard - United States Naval Academy - OH (Downstate Juniors)
Audrey St. Clair - United States Naval Academy - Libero/DS (Excel)

Southeastern Conference (SEC):
Erin Clark - University of Alabama - Libero/DS (AZ Storm)
Josie Imes - University of Alabama - OH (Circle City)
Audrey Simpson - University of Alabama - MB (A5)
Madi Benne - University of Arkansas - Libero/DS (MAVS KC)
Bella Knoernschild - University of Arkansas - Libero/DS (Elite Volleyball Academy)
Elsie Law - University of Arkansas - MB (Austin Skyline)
Maggie McCarroll - University of Arkansas - Setter (Austin Skyline)
Paisley Pavliska - University of Arkansas - OH (STVA)
Emma Gutke - Auburn University - MB (Sudden Impact)
Emily Keiran - Auburn University - Libero/DS (KIVA)
Macy McAmis - Auburn University - Libero/DS (Jupiter Elite)
Chierika Okororie - Auburn University - MB (Untouchables EPA)
Reese Shugart - Auburn University - OH (Upward Stars)
Nadiya Shelby - University of Florida - OPP/OH (Houston Skyline)
Gigi Artiles - University of Georgia - OH (Tribe)
Taylor Bruce - University of Georgia - OPP (NC Volleyball Academy)
Rylan Miller - University of Georgia - Libero/DS (OTVA)
Arianna Muoneke - University of Georgia - OH (Texas Tornadoes)
Bellamie Beus - University of Kentucky - OH (Idaho Crush)
Bryah Breaux - University of Kentucky - OPP (Metro)
Sidney Burley - University of Kentucky - Libero/DS (Minnesota Select)
Caroline Prihoda - University of Kentucky - Setter (Houston Skyline)
Gracison Saylors - University of Kentucky - MB (A5)
Kiley Brooks - Louisiana State University - Libero/DS (Dallas Skyline)
Hannah Lee - Louisiana State University - MB/OPP (TAV)
Katie Raymer - Louisiana State University - Libero/DS (Triangle)
Destiny Seaward - Louisiana State University - MB (Untouchables EPA)
Rileigh Butler - University of Mississippi (Ole Miss) - Libero/DS (Austin Skyline)
Jaidyn Hartsfield - University of Mississippi (Ole Miss) - OH (Madfrog)
Ryea Jackson - University of Mississippi (Ole Miss) - MB (Madfrog)
Coco Natarajan - University of Mississippi (Ole Miss) - Setter (Madfrog)
Sophie Taylor - University of Mississippi (Ole Miss) - OH (River Valley Juniors)
Cassidy Cage - Mississippi State University - MB (Sports Performance)
Adriana Jeanpierre - Mississippi State University - Setter (OTVA)
Marie Jones - Mississippi State University - OPP (Alabama Performance)
Paloma Routaboul - Mississippi State University - OH (International: Argentina)
Kyla Scharfman - Mississippi State University - Libero/DS (Alliance)
Piper Batie - University of Missouri - Setter (Ozark Juniors)
Millie Bauer - University of Missouri - MB (MAVS KC)
Eva Smith - University of Missouri - MB (Triangle)
Lydia Stahley - University of Missouri - OH/OPP (Team Indiana)
Halle Delince - University of Oklahoma - MB (Tribe)
DaMya Mann - University of Oklahoma - Setter (Alamo)
Jillian Bohannon - University of South Carolina - Setter (KIVA)
Madisyn Crnjac - University of South Carolina - OH (AZ Storm)
Ella Grivna - University of South Carolina - MB (MAVA)
Maggie Penn - University of South Carolina - Libero/DS (NC Volleyball Academy)
Emma Frietch - University of Tennessee - Libero/DS (NKYVC)
Jolene Oddo - University of Tennessee - MB (Triangle)
Camille Perry - University of Tennessee - MB (Dallas Skyline)
Anni Tang - University of Tennessee - MB (International: Australia)
Jade Williams - University of Tennessee - OPP (Tsunami)
Morgan Williams - University of Tennessee - OH (Metro)
Henley Anderson - University of Texas - OH (Austin Skyline)
Emma Cugino - University of Texas - Libero/DS (Mintonette)
Genevieve Harris - University of Texas - Setter (NC Volleyball Academy)
Lolufe Adedeji - Texas A&M University - MB (OK Charge)
Sara Bowcutt - Texas A&M University - OH (AZ Storm)
Brooke Lacewell - Texas A&M University - OPP (Dallas Skyline)
Gabi Rodriguez - Texas A&M University - Libero/DS (Madfrog)
Jenna Thedford - Texas A&M University - Libero/DS (Houston Skyline)
Jordin Southall - Vanderbilt University - OH (Game Point)
Madi Victoriano - Vanderbilt University - Setter (Dallas Skyline)

Southern Conference (SoCon):
Allie Davison - The Citadel - Setter (High Performance)
Emerson Hill - The Citadel - Libero/DS (OK Charge)
Emma Pastusic - The Citadel - OH (Triad United)
Cameron Reese - The Citadel - OH (Top Flight)
Kennedy Boatman - East Tennessee State University - Setter (Texas Legacy)
Karis Chatfield - East Tennessee State University - OH (FaR Out)
Darby Felts - East Tennessee State University - OH (Innerlight)
Phoenix Fogel - East Tennessee State University - MB (Dynasty)
Ryan Jomo - East Tennessee State University - Libero/DS (Top Select)
Morgan Baldridge - Furman University - Setter (Stars Carolinas)
Tiffany Helmer - Furman University - Libero/DS (Stars Carolinas)
Olivia Peterson - Furman University - OH/DS (Jupiter Elite)
Mikayla Miessler - Mercer University - OH (OTVA)
Brooklyn Palmer - Mercer University - OPP (Revolution Volleyball Academy)
Lexie Stotenbur - Mercer University - Setter (FaR Out)
Ella Burd - University of North Carolina at Greensboro - Libero/DS (Memphis Metro)
Hailey Clifton - University of North Carolina at Greensboro - OPP (Tampa United)
Beatriz Matos - University of North Carolina at Greensboro - MB (Tribe)
Lily Rodgers - University of North Carolina at Greensboro - OH (Top Select)
Molly Scott Cottrell - University of North Carolina at Greensboro - OPP (NC Coastal)
Hailey Thomsen - University of North Carolina at Greensboro - OPP (Tampa United)
Amyra Burchik - Samford University - OH (A5)
Peytyn Pyle - Samford University - MB (TAV Houston)
Haley Robinson - Samford University - OPP/MB (West Florida Waves)
Hazel Slusher - Samford University - OH/MB (M1)
Katelyn Stooksbury - Samford University - Libero/DS (K2)
Caroline Peterson - University of Tennessee at Chattanooga - Libero/DS (Stars Carolinas)
Taylor Baggett - Western Carolina University - OH (NC Volleyball Academy)
Ashlyn Cobb - Western Carolina University - OH (Tribe)
Aiyana Harris - Western Carolina University - MB (Dallas Skyline)
Leilani Ramos - Western Carolina University - Setter (Tribe)
Maddie Barrera - Wofford College - MB (Houston Skyline)
Makaylee Ruiz - Wofford College - Libero/DS (TAV)
Avery White - Wofford College - OPP (Premier Nebraska)

Southland Conference:
Katelyn Pritchard - East Texas A&M University - Setter (Texas Fierce Elite)
Sabine Wenzel - East Texas A&M University - MB (SMASH)
Katelyn Vo - Houston Christian University - Libero/DS (Excel)
Mya Cheatum - University of the Incarnate Word - OH (Austin Juniors)
Teddy-Raye Ewers - University of the Incarnate Word - OH (Excel)
Katelyn Hughes - Lamar University - Setter (Texas Fury)
Gabby St. Louis - Lamar University - OPP (Houston Stellar)
Aaniyah Kitchen - McNeese State University - MB (JET)
Valerie Yambao - McNeese State University - Setter (Game Point)
Armie Hall - University of New Orleans - OPP (Excel)
Ayen Nyuar - University of New Orleans - MB (International: Australia)
Amber Craig - Northwestern State University - OPP (Texas Legacy)
Anna Claire Hebert - Northwestern State University - Setter (Cajun Elite)
Olivia Nzioki - Northwestern State University - MB (Mizuno Club North)
Gillian Wolf - Northwestern State University - OH (Houston Juniors)
Daiany Gonzales - Southeastern Louisiana University - OPP (International: Bolivia)
Melina Gonzalez - Southeastern Louisiana University - OH (Texas Performance)
Claire King - Southeastern Louisiana University - MB (SOVC)
Lauren Ossmann - Southeastern Louisiana University - Setter (Wisconsin Elite)
Brea Payne - Southeastern Louisiana University - Setter (MOD)
Kaelyn Sharp - Southeastern Louisiana University - OH/DS (Infinity South)
Aniston Collins - Stephen F. Austin State University - Setter (Houston Skyline)
Erin Goodson - Stephen F. Austin State University - Libero/DS (Houston Stellar)
Asha King - Stephen F. Austin State University - MB (Texas Legacy)
Avery Koonsen - Stephen F. Austin State University - OH (Houston Stellar)
Abby Huddleston - Texas A&M University-Corpus Christi - MB (Excel)
Ella Loges - Texas A&M University-Corpus Christi - OH (Aspire)
Jordyn Smith - Texas A&M University-Corpus Christi - MB (Tropics)
Sydney Yohe - Texas A&M University-Corpus Christi - MB (Austin Juniors)
Jasmyn Walker - University of Texas Rio Grande Valley - MB (Houston Juniors)

Southwestern Athletic Conference (SWAC):
Kinslee Carter - Alabama A&M University - MB/OH (Memphis Metro)
Ivy Maxwell - Alabama A&M University - Setter (Houston Skyline)
Kennedy Moss - Alabama A&M University - OH/OPP/DS (Bama Elite)
Amaya Robinson - Alabama State University - OH/OPP (OTVA)
Karli Glover - University of Arkansas, Pine Bluff - DS/OH (MoCo Mavs)
London King - University of Arkansas, Pine Bluff - Setter (MoCo Mavs)
Aaniya Thornton - Bethune-Cookman University - Libero/DS (Austin Juniors)
Simone Robinson - Florida A&M University - Setter (TAV Houston)
Hailey Botello - Grambling State University - Setter/DS (Texas Fierce Elite)
Lainy Evans - Grambling State University - OH/OPP (East Carolina Juniors)
Jada Constanza - Jackson State University - OH/OPP (Jupiter Elite)
Maddie Moye - Jackson State University - OPP/MB (Jupiter Elite)
Neenah Burton - Prairie View A&M University - OH/DS (Tri-State Elite)
Aubrey Goode - Prairie View A&M University - Setter/DS (Austin Performance)
Kaiulani Sherrow - Texas Southern University - Setter/MB (A5 Gwinnett)

Summit League:
Maddie Bahnsen - University of Missouri-Kansas City - MB/OPP (NORCO)
Savy Repinski - University of Missouri-Kansas City - Setter (Madtown Juniors)
Hannah Wayment - University of Missouri-Kansas City - MB (Vegas Aces)
Cora Metcalf - University of Nebraska Omaha - OH/OPP
Dara Obeid - University of Nebraska Omaha - MB (International: Canada)
Kate Schroetlin - University of Nebraska Omaha - Libero/DS (NORCO)
Mackenzie Dufner - University of North Dakota - Setter (Empire)
Ellee McIntosh - University of North Dakota - OH/MB (Sanford Sports Academy)
Haley Patton - University of North Dakota - Libero/DS (Houston Stellar)
Allie Collins - North Dakota State University - MB (Front Range)
Morgan Engel - North Dakota State University - Setter/OPP (Kandi Elite)
Aryn Heeke - North Dakota State University - Libero/DS (KIVA)
Courtney Peters - North Dakota State University - OH (Kokoro)
Malayna Syverson - North Dakota State University - OH/MB (Kandi Elite)
Kendall Worwa - North Dakota State University - MB (Northern Lights)
Ana Appel - Oral Roberts University - Setter/OPP (Tulsa Charge)
Ashlyn Aseltine - Oral Roberts University - Libero/DS (Club Fusion)
Ciara Cunningham - Oral Roberts University - OPP/OH (Rockwood Thunder)
Khylie Remmenga - Oral Roberts University - MB (Performance Volleyball Academy)
Libby Ryan - Oral Roberts University - OH (KIVA)
Chloe Kmiecik - University of South Dakota - MB (KC Power)
Gabi Zachariasen - University of South Dakota - OH (Kairos)
Mallory Hartwig - South Dakota State University - OH (Sting United)
Marisa Michaelis - South Dakota State University - OPP (Minnesota Select)
Hannah Mlsna - South Dakota State University - OPP/MB (Madtown Juniors)
Kennedey Whitford - South Dakota State University - Libero/DS (Iowa Rockets)
Kira Brundage - University of St. Thomas - Libero/DS (Minnesota Select)
Maddy Jones - University of St. Thomas - MB (Idaho Crush)
Bryn Lunski - University of St. Thomas - OH (Minnesota Select)
Ella Thorson - University of St. Thomas - Setter (Kokoro)

Sun Belt Conference:
Eva Goodson - Appalachian State University - Setter (Prostyle Volleyball Academy)
Nevaeh Hays - Appalachian State University - MB (Stars Carolinas)
Amelia Mancino - Appalachian State University - OH (Winter Park)
Amber McClain - Appalachian State University - MB (Winter Park)
Lexi Shondell - Appalachian State University - Setter (Boiler Juniors)
Molly Teague - Appalachian State University - OPP/OH (Rhythm Volleyball Academy)
Iris Williams - Appalachian State University - Libero/DS (Union)
Calea Bush - Arkansas State University - MB/OPP (Texas Legacy)
Keira Garinger - Arkansas State University - OH (Rhythm Volleyball Academy)
Eden Roethel - Arkansas State University - MB (Milwaukee Sting)
Abby Bucey - Coastal Carolina University - Libero/DS (No Name)
Talia Johnson - Coastal Carolina University - OH (Club Savannah)
Bella Ekeler - Georgia Southern University - Setter/DS (K2)
Delaney Wingenbach - Georgia Southern University - OH/DS (Gainesville Juniors)
Sophia Johnson - Georgia State University - OPP (WAVE)
Aiden Lightburn - Georgia State University - MB/OPP (UpOnTop)
Selah Wadsworth - Georgia State University - OH/OPP (AZ Storm)
Brenna Corbin - James Madison University - Libero/DS (Blue Ridge)
Lindsey Large - James Madison University - Setter (Tennessee Performance)
Zharia Alleyne - University of Louisiana at Monroe - MB/OPP (OTVA)
Olivia Anderson - University of Louisiana at Monroe - Setter (FEVA)
Tatum Clay - University of Louisiana at Monroe - MB (East Valley Juniors)
Amelia Colón - University of Louisiana at Monroe - Libero/DS (FEVA)
Taylor Reid - University of Louisiana at Monroe - MB/OPP (M2)
Kennedy Scott - University of Louisiana at Monroe - OPP (Dallas Skyline)
Grace Troxell - University of Louisiana at Monroe - OH/OPP (The Academy)
Maci Gerboth - Marshall University - MB (Mintonette)
Addison Saunders - Marshall University - Libero/DS (Carolina Union)
Emma DiRocco - Old Dominion University - MB (Pittsburgh Elite)
Erica Duffy - Old Dominion University - Setter (Jacksonville Juniors)
Ashlyn Gent - Old Dominion University - Libero/DS (International: Canada)
Leilani Lawrence - Old Dominion University - OH (OTVA)
Abby MacMillan - Old Dominion University - OH (East Coast Power)
Avery Thiessen - Old Dominion University - MB (International: Canada)
Anabelle Cerny - University of South Alabama - Setter (Wisconsin Juniors)
Kathryn O'Toole - University of South Alabama - Libero/DS (KIVA)
Charli Pearce - University of South Alabama - MB/OPP (Mobile Storm)
Bennett Boulo - University of Southern Mississippi - Setter/OPP (Mobile Storm)
Alyssa Dampier - University of Southern Mississippi - MB/OPP (Infinity Volleyball Academy)
Kenzly Foote - Troy University - Libero/DS (Bama Elite)
Emma Merhi - Troy University - OH (Tribe)
Haley Nash - Troy University - Libero/DS (Houston Skyline BCS)
Isabella Ruether - Troy University - OH/OPP (Milwaukee Sting)

United Athletic Conference (UAC):
Jayla Jackson - Abilene Christian University - OH/OPP (TAV)
Garrah Prox - Abilene Christian University - MB (Texas Wave)
Isa Richardson - Abilene Christian University - MB (Red Storm)
Pierson Smith - Abilene Christian University - Setter (OK Charge)
Alyssa Todd - Abilene Christian University - OH (TAV)
Kaelynn Ashley - Austin Peay State University - OH (Texas Performance)
Malena Benz - Austin Peay State University - MB (Milwaukee Sting)
Callie Gardner - Austin Peay State University - Libero/DS (Drive Nation)
Cree Hollier - Austin Peay State University - MB (Legacy)
Berkley Bates - University of Central Arkansas - Libero/DS (San Antonio Juniors)
Madi Bryant - University of Central Arkansas - MB (Ozark Juniors)
Annie Hopkins - University of Central Arkansas - MB (Oklahoma Peak)
Josie Nichols - Eastern Kentucky University - OH (Elevation)
Sophia Richardson - Eastern Kentucky University - MB (NKYVC)
Becca Rogers - Eastern Kentucky University - MB (Vortex)
Kaylee Maikranz - University of North Alabama - Libero/DS (Tribe)
Onita Davis - Tarleton State University - MB (TAV)
Jacqui McClain - Tarleton State University - OH (Fieldhouse)
Kingsley Minus - Tarleton State University - Setter (United VBA)
Laci Schoen - Tarleton State University - OH (TAV Houston)
Megan Dougherty - University of Texas at Arlington - OH/OPP (A4)
Dixie Nessl - University of Texas at Arlington - MB (Rage)
Morgan Stitzer - University of Texas at Arlington - Libero/DS (Colorado Skyline)
Lucy Tricco - University of Texas at Arlington - Setter (Front Range)

West Coast Conference (WCC):
Romi Chlebecek - University of Denver - OH (Minnesota Select)
Abby Conklin - University of Denver - MB (Minnesota Select)
Katelyn Landis - University of Denver - MB (Winter Park)
Lily Van Hal - University of Denver - Setter (Kairos)
Dani Clewis - Gonzaga University - Setter (Legacy (CA))
Aurie Duncan - Gonzaga University - Setter/OPP (CPA)
Lucy Slavik - Gonzaga University - MB (Washington Volleyball Academy)
Adriana Dorn - University of the Pacific - Setter (OMNI)
Eliya Dev - Pepperdine University - OH (Bakersfield Volleyball Club)
Sullivan Leonard - Pepperdine University - MB (SC Elite)
Claire McNeal - Pepperdine University - OH (Arizona Sky)
Reese Poerner - Pepperdine University - OH (TAV)
Bella Rasi - Pepperdine University - Setter (SynergyForce)
Ellie Sandoz - Pepperdine University - MB (Idaho One)
Kalaweloilehua Chock - University of Portland - OH (Ku'ikahi)
Ellie Diehl Palmer - University of Portland - OPP/OH (Vision)
Josie Portela - University of Portland - MB (Arizona Sky)
Shaylee Stephen - University of Portland - MB (North Pacific Juniors)
Tallulah Carney - Saint Mary's College of California - OPP/MB (K2)
Lainey Day - Saint Mary's College of California - MB/OPP (Athena Volleyball Academy)
Kiana Johnson - Saint Mary's College of California - Libero/DS (Athena Volleyball Academy)
Mikayla Haner - Saint Mary's College of California - OH/DS (Aspire)
Emma Brewer - University of San Diego - OH (North Pacific Juniors)
Allie Dunnion - University of San Diego - MB (Arizona Sky)
Ella Fulton - University of San Diego - MB (Vision)
Ryann Knuth - University of San Diego - OH (Adversity)
Kalli Lipo - University of San Diego - Libero/DS (AZ Storm)
Addy Wiese - University of San Diego - Libero/DS (Rockwood Thunder)
Adelynn Legates - University of San Francisco - Setter (Vision)
Erin Robbins - University of San Francisco - MB (Iowa Select)
Lauryn Coleman - Santa Clara University - OPP (Sudden Impact)
Allison Dzieciuch - Santa Clara University - MB (Coast)
Kaiya Kearney - Santa Clara University - OH (Revolution Volleyball Academy)
Savannah Walker - Santa Clara University - OPP (Team Pineapple)
Orinayo Olukanmi - Seattle University - OH (Legacy (CA))
""".strip()