RPI_TEAM_NAME_ALIASES = {
    'Abilene Christian University': 'Abilene Christian',
    'Alabama A&M University': 'Alabama A&M',
    'Alabama State University': 'Alabama St.',
    'American University': 'American',
    'Arizona State University': 'Arizona St.',
    'Arkansas State University': 'Arkansas St.',
    'Auburn University': 'Auburn',
    'Ball State University': 'Ball St.',
    'Baylor University': 'Baylor',
    'Bellarmine University': 'Bellarmine',
    'Belmont University': 'Belmont',
    'Bethune Cookman University': 'Bethune-Cookman',
    'Binghamton University': 'Binghamton',
    'Boise State University': 'Boise St.',
    'Boston College': 'Boston College',
    'Bradley University': 'Bradley',
    'Brown University': 'Brown',
    'Bryant University': 'Bryant',
    'Bucknell University': 'Bucknell',
    'Butler University': 'Butler',
    'California Baptist University': 'California Baptist',
    'California State University, Northridge': 'CSUN',
    'Campbell University': 'Campbell',
    'Canisius University': 'Canisius',
    'Central Michigan University': 'Central Mich.',
    'Chicago State University': 'Chicago St.',
    'Clemson University': 'Clemson',
    'Cleveland State University': 'Cleveland St.',
    'Coastal Carolina University': 'Coastal Carolina',
    'Colgate University': 'Colgate',
    'College of William & Mary': 'William & Mary',
    'College of the Holy Cross': 'Holy Cross',
    'Colorado State University': 'Colorado St.',
    'Columbia University': 'Columbia',
    'Coppin State University': 'Coppin St.',
    'Cornell University': 'Cornell',
    'Creighton University': 'Creighton',
    'Dartmouth College': 'Dartmouth',
    'Davidson College': 'Davidson',
    'DePaul University': 'DePaul',
    'Delaware State University': 'Delaware St.',
    'Drake University': 'Drake',
    'Duke University': 'Duke',
    'Duquesne University': 'Duquesne',
    'East Carolina University': 'East Carolina',
    'East Texas A&M University': 'East Texas A&M',
    'Elon University': 'Elon',
    'Fairfield University': 'Fairfield',
    'Florida A&M University': 'Florida A&M',
    'Florida State University': 'Florida St.',
    'Fordham University': 'Fordham',
    'Furman University': 'Furman',
    'Gardner-Webb University': 'Gardner-Webb',
    'George Mason University': 'George Mason',
    'George Washington University': 'George Washington',
    'Georgetown University': 'Georgetown',
    'Georgia State University': 'Georgia St.',
    'Gonzaga University': 'Gonzaga',
    'Grand Canyon University': 'Grand Canyon',
    'Hampton University': 'Hampton',
    'Harvard University': 'Harvard',
    'High Point University': 'High Point',
    'Hofstra University': 'Hofstra',
    'Houston Christian University': 'Houston Christian',
    'Howard University': 'Howard',
    'Idaho State University': 'Idaho St.',
    'Illinois State University': 'Illinois St.',
    'Indiana State University': 'Indiana St.',
    'Indiana University': 'Indiana',
    'Iona University': 'Iona',
    'Iowa State University': 'Iowa St.',
    'Jackson State University': 'Jackson St.',
    'Jacksonville State University': 'Jacksonville St.',
    'Jacksonville University': 'Jacksonville',
    'James Madison University': 'James Madison',
    'Kansas State University': 'Kansas St.',
    'Kennesaw State University': 'Kennesaw St.',
    'Kent State University': 'Kent St.',
    'Lafayette College': 'Lafayette',
    'Lamar University': 'Lamar University',
    'Le Moyne College': 'Le Moyne',
    'Lehigh University': 'Lehigh',
    'Liberty University': 'Liberty',
    'Lindenwood University': 'Lindenwood',
    'Lipscomb University': 'Lipscomb',
    'Louisiana Tech University': 'Louisiana Tech',
    'Loyola University Chicago': 'Loyola Chicago',
    'Loyola University Maryland': 'Loyola Maryland',
    'Manhattan University': 'Manhattan',
    'Marist University': 'Marist',
    'Marquette University': 'Marquette',
    'Marshall University': 'Marshall',
    'Mercer University': 'Mercer',
    'Merrimack College': 'Merrimack',
    'Michigan State University': 'Michigan St.',
    'Mississippi State University': 'Mississippi St.',
    'Missouri State University': 'Missouri St.',
    'Montana State University': 'Montana St.',
    'Morehead State University': 'Morehead St.',
    'Morgan State University': 'Morgan St.',
    'Murray State University': 'Murray St.',
    'New Jersey Institute of Technology': 'NJIT',
    'New Mexico State University': 'New Mexico St.',
    'Niagara University': 'Niagara',
    'Norfolk State University': 'Norfolk St.',
    'North Dakota State University': 'North Dakota St.',
    'Northeastern University': 'Northeastern',
    'Northwestern State University': 'Northwestern St.',
    'Northwestern University': 'Northwestern',
    'Oakland University': 'Oakland',
    'Ohio University': 'Ohio',
    'Old Dominion University': 'Old Dominion',
    'Oral Roberts University': 'Oral Roberts',
    'Oregon State University': 'Oregon St.',
    'Pepperdine University': 'Pepperdine',
    'Portland State University': 'Portland St.',
    'Presbyterian College': 'Presbyterian',
    'Princeton University': 'Princeton',
    'Providence College': 'Providence',
    'Purdue University': 'Purdue',
    'Purdue University Fort Wayne': 'Purdue Fort Wayne',
    'Quinnipiac University': 'Quinnipiac',
    'Radford University': 'Radford',
    'Rice University': 'Rice',
    'Rider University': 'Rider',
    'Robert Morris University': 'Robert Morris',
    'Rutgers': 'Rutgers',
    'Sacred Heart University': 'Sacred Heart',
    'Saint Louis University': 'Saint Louis',
    "Saint Peter's University": "Saint Peter's",
    'Samford University': 'Samford',
    'San Diego State University': 'San Diego St.',
    'San Jose State University': 'San Jose St.',
    'Santa Clara University': 'Santa Clara',
    'Seton Hall University': 'Seton Hall',
    'Siena University': 'Siena',
    'South Carolina State University': 'South Carolina St.',
    'South Dakota State University': 'South Dakota St.',
    'Southern Utah University': 'Southern Utah',
    'Stanford University': 'Stanford',
    'Stetson University': 'Stetson',
    'Stonehill College': 'Stonehill',
    'Stony Brook University': 'Stony Brook',
    'Syracuse University': 'Syracuse',
    'Tarleton State University': 'Tarleton St.',
    'Temple University': 'Temple',
    'Tennessee State University': 'Tennessee St.',
    'Texas A&M University': 'Texas A&M',
    'Texas Southern University': 'Texas Southern',
    'Texas State University': 'Texas St.',
    'Texas Tech University': 'Texas Tech',
    'The Citadel': 'The Citadel',
    'The Ohio State University': 'Ohio St.',
    'Towson University': 'Towson',
    'Troy University': 'Troy',
    'Tulane University': 'Tulane',
    'University at Albany': 'UAlbany',
    'University at Buffalo': 'Buffalo',
    'University of Akron': 'Akron',
    'University of Alabama': 'Alabama',
    'University of Arizona': 'Arizona',
    'University of Arkansas': 'Arkansas',
    'University of Cincinnati': 'Cincinnati',
    'University of Colorado': 'Colorado',
    'University of Connecticut': 'UConn',
    'University of Dayton': 'Dayton',
    'University of Delaware': 'Delaware',
    'University of Denver': 'Denver',
    'University of Evansville': 'Evansville',
    'University of Florida': 'Florida',
    'University of Georgia': 'Georgia',
    'University of Hawaii': 'Hawaii',
    'University of Houston': 'Houston',
    'University of Idaho': 'Idaho',
    'University of Illinois': 'Illinois',
    'University of Iowa': 'Iowa',
    'University of Kansas': 'Kansas',
    'University of Kentucky': 'Kentucky',
    'University of Louisville': 'Louisville',
    'University of Maryland': 'Maryland',
    'University of Maryland, Baltimore County':'UMBC',
    'University of Memphis': 'Memphis',
    'University of Michigan': 'Michigan',
    'University of Minnesota': 'Minnesota',
    'University of Missouri': 'Missouri',
    'University of Montana': 'Montana',
    'University of Nebraska': 'Nebraska',
    'University of New Hampshire': 'New Hampshire',
    'University of New Haven': 'New Haven',
    'University of New Mexico': 'New Mexico',
    'University of New Orleans': 'New Orleans',
    'University of North Carolina': 'North Carolina',
    'University of North Dakota': 'North Dakota',
    'University of North Florida': 'North Florida',
    'University of North Texas': 'North Texas',
    'University of Notre Dame': 'Notre Dame',
    'University of Oklahoma': 'Oklahoma',
    'University of Oregon': 'Oregon',
    'University of Pittsburgh': 'Pittsburgh',
    'University of Portland': 'Portland',
    'University of Rhode Island': 'Rhode Island',
    'University of San Diego': 'San Diego',
    'University of San Francisco': 'San Francisco',
    'University of South Alabama': 'South Alabama',
    'University of South Carolina': 'South Carolina',
    'University of South Dakota': 'South Dakota',
    'University of South Florida': 'South Fla.',
    'University of Southern California': 'Southern California',
    'University of Tennessee': 'Tennessee',
    'University of Texas': 'Texas',
    'University of Toledo': 'Toledo',
    'University of Tulsa': 'Tulsa',
    'University of Utah': 'Utah',
    'University of Virginia': 'Virginia',
    'University of Washington': 'Washington',
    'University of Wisconsin': 'Wisconsin',
    'University of Wyoming': 'Wyoming',
    'University of the Pacific': 'Pacific',
    'Utah State University': 'Utah St.',
    'Utah Tech University': 'Utah Tech',
    'Utah Valley University': 'Utah Valley',
    'Valparaiso University': 'Valparaiso',
    'Vanderbilt University': 'Vanderbilt',
    'Villanova University': 'Villanova',
    'Virginia Tech': 'Virginia Tech',
    'Wake Forest University': 'Wake Forest',
    'Washington State University': 'Washington St.',
    'Weber State University': 'Weber St.',
    'West Virginia University': 'West Virginia',
    'Wichita State University': 'Wichita St.',
    'Winthrop University': 'Winthrop',
    'Wofford College': 'Wofford',
    'Wright State University': 'Wright St.',
    'Xavier University': 'Xavier',
    'Yale University': 'Yale',
    'Youngstown State University': 'Youngstown St.',
    'Alcorn State University': 'Alcorn',
    'Appalachian State University': 'App State',
    'Austin Peay State University': 'Austin Peay',
    'Bowling Green State University': 'Bowling Green',
    'Brigham Young University': 'BYU',
    'California Polytechnic State University': 'Cal Poly',
    'California State University, Fullerton': 'Cal St. Fullerton',
    'Central Connecticut State University': 'Central Conn. St.',
    'Charleston Southern University': 'Charleston So.',
    'College of Charleston': 'Col. of Charleston',
    'East Tennessee State University': 'ETSU',
    'Eastern Illinois University': 'Eastern Ill.',
    'Eastern Michigan University': 'Eastern Mich.',
    'Eastern Washington University': 'Eastern Wash.',
    'Florida Atlantic University': 'Fla. Atlantic',
    'Louisiana State University': 'LSU',
    'Middle Tennessee State University': 'Middle Tenn.',
    'Mississippi Valley State University': 'Mississippi Val.',
    'Northern Arizona University': 'Northern Ariz.',
    'California State University, Bakersfield': 'CSU Bakersfield',
    'California State University, Fresno': 'Fresno St.',
    'California State University, Long Beach': 'Long Beach St.',
    'California State University, Sacramento': 'Sacramento St.',
    'Eastern Kentucky University': 'Eastern Ky.',
    'Fairleigh Dickinson University': 'FDU',
    'Florida Gulf Coast University': 'FGCU',
    'Florida International University': 'FIU',
    'Georgia Institute of Technology': 'Georgia Tech',
    'Georgia Southern University': 'Ga. Southern',
    'Grambling State University': 'Grambling',
    'Indiana University Indianapolis': 'IU Indy',
    'Long Island University (LIU)': 'LIU',
    'Loyola Marymount University': 'LMU (CA)',
    'McNeese State University': 'McNeese',
    'Mercyhurst University[c]': 'Mercyhurst',
    'Miami University (Ohio)': 'Miami (OH)',
    'New Jersey Institute of Technology': 'NJIT',
    'Nicholls State University': 'Nicholls',
    'North Carolina A&T State University': 'N.C. A&T',
    'North Carolina Central University': 'N.C. Central',
    'North Carolina State University': 'NC State',
    'Northern Illinois University': 'NIU',
    'Northern Kentucky University': 'Northern Ky.',
    'Pennsylvania State University': 'Penn St.',
    'Prairie View A&M University': 'Prairie View',
    'Queens University of Charlotte': 'Queens (NC)',
    'Saint Francis University (Saint Francis (PA))[n]': 'Saint Francis',
    "Saint Mary's College of California": "Saint Mary's (CA)",
    'Sam Houston State University': 'Sam Houston',
    'Seattle University': 'Seattle U',
    'Southeast Missouri State University': 'Southeast Mo. St.',
    'Southeastern Louisiana University': 'Southeastern La.',
    'Southern Illinois University Carbondale': 'Southern Ill.',
    'Southern Illinois University Edwardsville': 'SIUE',
    'Southern Methodist University': 'SMU',
    'Southern University': 'Southern U.',
    "St. John's University": "St. John's (NY)",
    'Stephen F. Austin State University': 'SFA',
    'Tennessee Technological University': 'Tennessee Tech',
    'Texas A&M University-Corpus Christi': 'A&M-Corpus Christi',
    'Texas Christian University': 'TCU',
    'The University of Southern Mississippi': 'Southern Miss.',
    'United States Air Force Academy': 'Air Force',
    'United States Military Academy': 'Army West Point',
    'United States Naval Academy': 'Navy',
    'University at Albany': 'UAlbany',
    'University of Alabama at Birmingham': 'UAB',
    'University of Arkansas at Little Rock (Little Rock)': 'Little Rock',
    'University of Arkansas, Pine Bluff': 'Ark.-Pine Bluff',
    'University of California, Berkeley': 'California',
    'University of California, Davis': 'UC Davis',
    'University of California, Irvine': 'UC Irvine',
    'University of California, Los Angeles': 'UCLA',
    'University of California, Riverside': 'UC Riverside',
    'University of California, San Diego': 'UC San Diego',
    'University of California, Santa Barbara': 'UC Santa Barbara',
    'University of Central Arkansas': 'Central Ark.',
    'University of Central Florida': 'UCF',
    'University of Illinois Chicago (UIC)': 'UIC',
    'University of Louisiana at Lafayette': 'Louisiana',
    'University of Louisiana at Monroe': 'ULM',
    'University of Maryland Eastern Shore (UMES or Maryland Eastern Shore)': 'UMES',
    'University of Maryland, Baltimore County': 'UMBC',
    'University of Miami': 'Miami (FL)',
    'University of Mississippi (Ole Miss)': 'Ole Miss',
    'University of Missouri-Kansas City': 'Kansas City',
    'University of Nebraska Omaha': 'Omaha',
    'University of Nevada, Las Vegas': 'UNLV',
    'University of Nevada, Reno': 'Nevada',
    'University of North Alabama': 'North Ala.',
    'University of North Carolina Asheville': 'UNC Asheville',
    'University of North Carolina Wilmington': 'UNCW',
    'University of North Carolina at Charlotte': 'Charlotte',
    'University of North Carolina at Greensboro': 'UNC Greensboro',
    'University of Northern Colorado': 'Northern Colo.',
    'University of Northern Iowa': 'UNI',
    'University of Pennsylvania': 'Penn',
    'University of South Carolina Upstate': 'USC Upstate',
    'University of South Florida': 'South Fla.',
    'University of Southern Indiana': 'Southern Ind.',
    'University of St. Thomas': 'St. Thomas (MN)',
    'University of Tennessee at Chattanooga': 'Chattanooga',
    'University of Tennessee at Martin (UT Martin)': 'UT Martin',
    'University of Texas Rio Grande Valley': 'UTRGV',
    'University of Texas at Arlington': 'UT Arlington',
    'University of Texas at El Paso': 'UTEP',
    'University of Texas at San Antonio': 'UTSA',
    'University of West Georgia': 'West Ga.',
    'University of Wisconsin-Green Bay': 'Green Bay',
    'University of Wisconsin-Milwaukee': 'Milwaukee',
    'University of the Incarnate Word': 'UIW',
    'Virginia Commonwealth University': 'VCU',
    'Western Carolina University': 'Western Caro.',
    'Western Illinois University': 'Western Ill.',
    'Western Kentucky University': 'Western Ky.',
    'Western Michigan University': 'Western Mich.',
}